using FluentMigrator;
using NpgsqlTypes;

namespace aws_migration.migrations;

[Migration(20230717212800)]
public class AddOnDemandPricingTables2 : Migration {
    public override void Up()
    {
        Create.Table("OnDemandPricing").WithDescription("on demand pricing data")
            .WithColumn("Id").AsInt64().PrimaryKey().Identity()
            .WithColumn("CreatedAt").AsCustom("timestamptz").NotNullable()
            .WithColumn("SKU").AsString().Nullable()
            .WithColumn("OnDemandCsvRowsId").AsInt64().ForeignKey("OnDemandCsvRows", "Id")
            .WithColumn("OfferTermCode").AsString().Nullable()
            .WithColumn("RateCode").AsString().Nullable()
            .WithColumn("TermType").AsString().Nullable()
            .WithColumn("PriceDescription").AsString().Nullable()
            .WithColumn("EffectiveDate").AsDateTime2().Nullable()
            .WithColumn("StartingRange").AsString().Nullable()
            .WithColumn("EndingRange").AsString().Nullable()
            .WithColumn("Unit").AsString().Nullable()
            .WithColumn("PricePerUnit").AsString().Nullable()
            .WithColumn("Currency").AsString().Nullable()
            .WithColumn("RelatedTo").AsString().Nullable()
            .WithColumn("LeaseContractLength").AsString().Nullable()
            .WithColumn("PurchaseOption").AsString().Nullable()
            .WithColumn("OfferingClass").AsString().Nullable()
            .WithColumn("Product Family").AsString().Nullable()
            .WithColumn("serviceCode").AsString().Nullable()
            .WithColumn("Location").AsString().Nullable()
            .WithColumn("Location Type").AsString().Nullable()
            .WithColumn("Instance Type").AsString().Nullable()
            .WithColumn("Current Generation").AsString().Nullable()
            .WithColumn("Instance Family").AsString().Nullable()
            .WithColumn("vCPU").AsInt64().Nullable()
            .WithColumn("Physical Processor").AsString().Nullable()
            .WithColumn("Clock Speed").AsString().Nullable()
            .WithColumn("Memory").AsString().Nullable()
            .WithColumn("Storage").AsString().Nullable()
            .WithColumn("Network Performance").AsString().Nullable()
            .WithColumn("Processor Architecture").AsString().Nullable()
            .WithColumn("Storage Media").AsString().Nullable()
            .WithColumn("Volume Type").AsString().Nullable()
            .WithColumn("Max Volume Size").AsString().Nullable()
            .WithColumn("Max IOPS/volume").AsString().Nullable()
            .WithColumn("Max IOPS Burst Performance").AsString().Nullable()
            .WithColumn("Max throughput/volume").AsString().Nullable()
            .WithColumn("Provisioned").AsString().Nullable()
            .WithColumn("Tenancy").AsString().Nullable()
            .WithColumn("Operating System").AsString().Nullable()
            .WithColumn("License Model").AsString().Nullable()
            .WithColumn("Group").AsString().Nullable()
            .WithColumn("Group Description").AsString().Nullable()
            .WithColumn("usageType").AsString().Nullable()
            .WithColumn("operation").AsString().Nullable()
            .WithColumn("AvailabilityZone").AsString().Nullable()
            .WithColumn("CapacityStatus").AsString().Nullable()
            .WithColumn("ClassicNetworkingSupport").AsString().Nullable()
            .WithColumn("Dedicated EBS Throughput").AsString().Nullable()
            .WithColumn("ECU").AsString().Nullable()
            .WithColumn("Enhanced Networking Supported").AsString().Nullable()
            .WithColumn("GPU").AsString().Nullable()
            .WithColumn("GPU Memory").AsString().Nullable()
            .WithColumn("Instance").AsString().Nullable()
            .WithColumn("Instance Capacity - 10xlarge").AsString().Nullable()
            .WithColumn("Instance Capacity - 12xlarge").AsString().Nullable()
            .WithColumn("Instance Capacity - 16xlarge").AsString().Nullable()
            .WithColumn("Instance Capacity - 18xlarge").AsString().Nullable()
            .WithColumn("Instance Capacity - 24xlarge").AsString().Nullable()
            .WithColumn("Instance Capacity - 2xlarge").AsString().Nullable()
            .WithColumn("Instance Capacity - 32xlarge").AsString().Nullable()
            .WithColumn("Instance Capacity - 4xlarge").AsString().Nullable()
            .WithColumn("Instance Capacity - 8xlarge").AsString().Nullable()
            .WithColumn("Instance Capacity - 9xlarge").AsString().Nullable()
            .WithColumn("Instance Capacity - large").AsString().Nullable()
            .WithColumn("Instance Capacity - medium").AsString().Nullable()
            .WithColumn("Instance Capacity - metal").AsString().Nullable()
            .WithColumn("Instance Capacity - xlarge").AsString().Nullable()
            .WithColumn("instanceSKU").AsString().Nullable()
            .WithColumn("Intel AVX2 Available").AsString().Nullable()
            .WithColumn("Intel AVX Available").AsString().Nullable()
            .WithColumn("Intel Turbo Available").AsString().Nullable()
            .WithColumn("MarketOption").AsString().Nullable()
            .WithColumn("Normalization Size Factor").AsString().Nullable()
            .WithColumn("Physical Cores").AsString().Nullable()
            .WithColumn("Pre Installed S/W").AsString().Nullable()
            .WithColumn("Processor Features").AsString().Nullable()
            .WithColumn("Product Type").AsString().Nullable()
            .WithColumn("Region Code").AsString().Nullable()
            .WithColumn("Resource Type").AsString().Nullable()
            .WithColumn("serviceName").AsString().Nullable()
            .WithColumn("SnapshotArchiveFeeType").AsString().Nullable()
            .WithColumn("Volume API Name").AsString().Nullable()
            .WithColumn("VPCNetworkingSupport").AsString().Nullable();
    }

    public override void Down()
    {
        Delete.Table("OnDemandPricing");
    }
}