services:
  restapi-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "3000:3000"
      - "3001:3001"
    expose:
      - "3000"
      - "3001"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:3000;https://0.0.0.0:3001
    env_file:
      - ./config/dev/aws-secret.env
      - ./config/dev/github-secret.env
      - ./config/dev/postgres-secret.env
  restapi-prod:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "3000:3000"
      - "3001:3001"
    expose:
      - "3000"
      - "3001"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:3000;https://0.0.0.0:3001
    env_file:
      - ./config/dev/aws-secret.env
      - ./config/dev/github-secret.env
      - ./config/dev/postgres-secret.env
    
    
