COPY "OnDemandPricing" 
    ("CreatedAt",
     "SKU",
     "OnDemandCsvFilesId",
     "OnDemandCsvRowsId",
     "OfferTermCode",
     "RateCode",
     "TermType",
     "PriceDescription",
     "EffectiveDate",
     "StartingRange",
     "EndingRange",
     "Unit",
     "PricePerUnit",
     "Currency",
     "RelatedTo",
     "LeaseContractLength",
     "PurchaseOption",
     "OfferingClass",
     "Product Family",
     "serviceCode",
     "Location",
     "Location Type",
     "Instance Type",
     "Current Generation",
     "Instance Family",
     "vCPU",
     "Physical Processor",
     "Clock Speed",
     "Memory",
     "Storage",
     "Network Performance",
     "Processor Architecture",
     "Tenancy",
     "Operating System",
     "License Model",
     "GPU",
     "GPU Memory",
     "instanceSKU",
     "MarketOption",
     "Normalization Size Factor",
     "Physical Cores",
     "Processor Features",
     "Region Code",
     "serviceName")
    FROM STDIN (FORMAT BINARY)
