with hashed as (select "Instance Type",
                       "SKU",
                       "EffectiveDate",
                       "PricePerUnit",
                       "OfferTermCode",
                       "RateCode",
                       "OnDemandCsvFilesId",
                       "OnDemandCsvRowsId",
                       "TermType",
                       "PriceDescription",
                       --regexp_match("PriceDescription", '^\$[0-9\.]+','') priceDescriptionRegex,
                       regexp_match("PriceDescription", 'SQL') priceDescriptionRegex,
                       regexp_match("PriceDescription", 'SQL') is null as regexTest,
                       "StartingRange",
                       "EndingRange",
                       "Unit",
                       "Currency",
                       "RelatedTo",
                       "LeaseContractLength",
                       "PurchaseOption",
                       "OfferingClass",
                       "Product Family",
                       "serviceCode",
                       "Location",
                       "Location Type",
                       "Current Generation",
                       "Instance Family",
                       "vCPU",
                       "Physical Processor",
                       "Clock Speed",
                       "Memory",
                       "Storage",
                       "Network Performance",
                       "Processor Architecture",
                       "Tenancy",
                       "Operating System",
                       "License Model",
                       "GPU",
                       "GPU Memory",
                       "instanceSKU",
                       "MarketOption",
                       "Normalization Size Factor",
                       "Physical Cores",
                       "Processor Features",
                       "Region Code",
                       "serviceName"
                        ,
                       md5(ROW (
                           "Instance Type",
                           "Tenancy",
                           "Operating System",
                           "License Model",
                           "PurchaseOption",
                           "OfferingClass" ,
                           "PurchaseOption",
                           "LeaseContractLength",
                           "Region Code",
                           "Unit"
                           )::TEXT) as pricegroup
                from "OnDemandPricing"
                where "Instance Family" = 'GPU instance'
--                   and "Unit" = 'Hrs'
--                   and "Region Code" = 'us-east-1'
--                   and "Current Generation" = 'Yes'
                  and "PricePerUnit" > '$0.00'
                and regexp_match("PriceDescription", 'SQL') is null
--                   and regexp_matches("PriceDescription", '(sql|SQL)')
                ),
     calced as (select pricegroup,
                       rank()
                       over (partition by pricegroup, "EffectiveDate", "PricePerUnit" order by random()) as duprank,
                       "Instance Type",
                       "SKU",
                       "EffectiveDate",
                       "PricePerUnit",
                       min("PricePerUnit") over (partition by pricegroup)                                   minPrice,
                       max("PricePerUnit") over (partition by pricegroup)                                   maxPrice,
                       "OfferTermCode",
                       "RateCode",
                       "OnDemandCsvFilesId",
                       "OnDemandCsvRowsId",
                       "TermType",
                       "PriceDescription",
                       priceDescriptionRegex,
                       regexTest,
                       "StartingRange",
                       "EndingRange",
                       "Unit",
                       "Currency",
                       "RelatedTo",
                       "LeaseContractLength",
                       "PurchaseOption",
                       "OfferingClass",
                       "Product Family",
                       "serviceCode",
                       "Location",
                       "Location Type",
                       "Current Generation",
                       "Instance Family",
                       "vCPU",
                       "Physical Processor",
                       "Clock Speed",
                       "Memory",
                       "Storage",
                       "Network Performance",
                       "Processor Architecture",
                       "Tenancy",
                       "Operating System",
                       "License Model",
                       "GPU",
                       "GPU Memory",
                       "instanceSKU",
                       "MarketOption",
                       "Normalization Size Factor",
                       "Physical Cores",
                       "Processor Features",
                       "Region Code",
                       "serviceName"
                from hashed)
select pricegroup,
       duprank,
       "Instance Type",
       "SKU",
       "EffectiveDate",
       "PricePerUnit",
       minPrice,
       maxPrice,
       "OfferTermCode",
       "RateCode",
       "OnDemandCsvFilesId",
       "OnDemandCsvRowsId",
       "TermType",
       "PriceDescription",
       priceDescriptionRegex,
       regexTest,
       "StartingRange",
       "EndingRange",
       "Unit",
       "Currency",
       "RelatedTo",
       "LeaseContractLength",
       "PurchaseOption",
       "OfferingClass",
       "Product Family",
       "serviceCode",
       "Location",
       "Location Type",
       "Current Generation",
       "Instance Family",
       "vCPU",
       "Physical Processor",
       "Clock Speed",
       "Memory",
       "Storage",
       "Network Performance",
       "Processor Architecture",
       "Tenancy",
       "Operating System",
       "License Model",
       "GPU",
       "GPU Memory",
       "instanceSKU",
       "MarketOption",
       "Normalization Size Factor",
       "Physical Cores",
       "Processor Features",
       "Region Code",
       "serviceName"
from calced
  where duprank = 1
and minPrice <> maxPrice
order by "Instance Type",
         pricegroup,
         "EffectiveDate"