using System.ComponentModel;
using CsvHelper.Configuration.Attributes;

public class OnDemandPrice
{
    [Name("Id")] public string Id;
    [Name("CreatedAt")] public DateTime CreatedAt;
    [Name("SKU")] public string SKU;
    [Name("OnDemandCsvRowsId")] public string OnDemandCsvRowsId;
    [Name("OfferTermCode")] public string OfferTermCode;
    [Name("RateCode")] public string RateCode;
    [Name("TermType")] public string TermType;
    [Name("PriceDescription")] public string PriceDescription;
    [Name("EffectiveDate")] public string EffectiveDate;
    [Name("StartingRange")] public string StartingRange;
    [Name("EndingRange")] public string EndingRange;
    [Name("Unit")] public string Unit;
    [Name("PricePerUnit")] public string PricePerUnit;
    [Name("Currency")] public string Currency;
    [Name("RelatedTo")] public string RelatedTo;
    [Name("LeaseContractLength")] public string LeaseContractLength;
    [Name("PurchaseOption")] public string PurchaseOption;
    [Name("OfferingClass")] public string OfferingClass;
    [Name("Product Family")] public string ProductFamily;
    [Name("serviceCode")] public string serviceCode;
    [Name("Location")] public string Location;
    [Name("Location Type")] public string LocationType;
    [Name("Instance Type")] public string InstanceType;
    [Name("Current Generation")] public string CurrentGeneration;
    [Name("Instance Family")] public string InstanceFamily;
    [Name("vCPU")] public string vCPU;
    [Name("Physical Processor")] public string PhysicalProcessor;
    [Name("Clock Speed")] public string ClockSpeed;
    [Name("Memory")] public string Memory;
    [Name("Storage")] public string Storage;
    [Name("Network Performance")] public string NetworkPerformance;
    [Name("Processor Architecture")] public string ProcessorArchitecture;
    [Name("Tenancy")] public string Tenancy;
    [Name("Operating System")] public string OperatingSystem;
    [Name("License Model")] public string LicenseModel;
    [Name("GPU")] public string GPU;
    [Name("GPU Memory")] public string GpuMemory;
    [Name("instanceSKU")] public string instanceSKU;
    [Name("MarketOption")] public string MarketOption;
    [Name("Normalization Size Factor")] public string NormalizationSizeFactor;
    [Name("Physical Cores")] public string PhysicalCores;
    [Name("Processor Features")] public string ProcessorFeatures;
    [Name("Region Code")] public string RegionCode;
    [Name("serviceName")] public string serviceName;
}