on:
  push:
    branches:
      - master
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
name: Create release pr
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          tags: ghcr.io/ptcdevs/aws-restapi:latest
          push: false
  release-please:
    needs:
      - build-app
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: release-please-action