on:
  push:
    branches:
      - master
      - new-restapi
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
name: Create release pr
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
      - run: dotnet build csharp/aws-restapi
#  release-please:
#    needs:
#      - build-app
#    runs-on: ubuntu-latest
#    steps:
#      - uses: google-github-actions/release-please-action@v3
#        with:
#          release-type: simple
#          package-name: release-please-action